services:

  #############################################
  # Home Assistant container
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"

    volumes:
      - ./homeAssistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro

    restart: unless-stopped

    privileged: true

    network_mode: host

  #############################################
  # MQTT Mosquitto container
  mosquitto:
    container_name: mqtt
    image: eclipse-mosquitto

    ports:
      - 1883:1883
      - 9001:9001

    volumes:
      # Config
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      # Data and log
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

  #############################################
  # ZigBee2MQTT container
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt

    ports:
      - 8080:8080

    depends_on:
      - mosquitto

    volumes:
      - ./zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro

    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0 # Usb ZigBee dongle (can be found using 'ls /dev/ttyUSB*' command)

    restart: unless-stopped

volumes:
  mosquitto_config:
  mosquitto_data:
  mosquitto_log:
  zigbee_data:
